POST http://localhost:3000/api/v1/espacio
# Tipo de post que queremos hacer, en este caso json
Content-Type: application/json

{
    "edificio": "B",
    "aula": "A"
}

##########################
GET http://localhost:3000/api/v1/espacio